"""Initial schema

Revision ID: a7f5e35e73a6
Revises: 
Create Date: 2026-07-13 16:08:05.785296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7f5e35e73a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_table('crawls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('seed_url', sa.String(length=2048), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crawls_id'), 'crawls', ['id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('status_name', sa.String(length=100), nullable=True),
    sa.Column('indexability', sa.Enum('INDEXABLE', 'NON_INDEXABLE', name='indexabilitystatus'), nullable=True),
    sa.Column('indexability_status', sa.Enum('NONE', 'NOINDEX', 'CANONICALISED', 'ROBOTS_BLOCKED', 'CLIENT_ERROR', 'SERVER_ERROR', name='nonindexablereason'), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=32), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('text_to_html_ratio', sa.Float(), nullable=True),
    sa.Column('crawl_depth', sa.Integer(), nullable=True),
    sa.Column('folder_depth', sa.Integer(), nullable=True),
    sa.Column('title_1', sa.String(length=2048), nullable=True),
    sa.Column('title_1_length', sa.Integer(), nullable=True),
    sa.Column('title_1_pixel_width', sa.Integer(), nullable=True),
    sa.Column('meta_desc_1', sa.Text(), nullable=True),
    sa.Column('meta_desc_1_length', sa.Integer(), nullable=True),
    sa.Column('meta_desc_1_pixel_width', sa.Integer(), nullable=True),
    sa.Column('meta_keyword_1', sa.Text(), nullable=True),
    sa.Column('meta_keyword_1_length', sa.Integer(), nullable=True),
    sa.Column('h1_1', sa.Text(), nullable=True),
    sa.Column('h1_1_length', sa.Integer(), nullable=True),
    sa.Column('h1_2', sa.Text(), nullable=True),
    sa.Column('h1_2_length', sa.Integer(), nullable=True),
    sa.Column('h2_1', sa.Text(), nullable=True),
    sa.Column('h2_1_length', sa.Integer(), nullable=True),
    sa.Column('h2_2', sa.Text(), nullable=True),
    sa.Column('h2_2_length', sa.Integer(), nullable=True),
    sa.Column('meta_robots_1', sa.String(length=255), nullable=True),
    sa.Column('x_robots_tag_1', sa.String(length=255), nullable=True),
    sa.Column('canonical_link_element_1', sa.String(length=2048), nullable=True),
    sa.Column('rel_next_1', sa.String(length=2048), nullable=True),
    sa.Column('rel_prev_1', sa.String(length=2048), nullable=True),
    sa.Column('dir_index', sa.Boolean(), nullable=True),
    sa.Column('dir_noindex', sa.Boolean(), nullable=True),
    sa.Column('dir_follow', sa.Boolean(), nullable=True),
    sa.Column('dir_nofollow', sa.Boolean(), nullable=True),
    sa.Column('dir_noarchive', sa.Boolean(), nullable=True),
    sa.Column('dir_nosnippet', sa.Boolean(), nullable=True),
    sa.Column('dir_noodp', sa.Boolean(), nullable=True),
    sa.Column('dir_nootranstale', sa.Boolean(), nullable=True),
    sa.Column('dir_noimageindex', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_id'), 'pages', ['id'], unique=False)
    op.create_index(op.f('ix_pages_url'), 'pages', ['url'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_id'), 'images', ['id'], unique=False)
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.Integer(), nullable=False),
    sa.Column('source_page_id', sa.Integer(), nullable=False),
    sa.Column('destination_url', sa.String(length=2048), nullable=False),
    sa.Column('anchor_text', sa.Text(), nullable=True),
    sa.Column('is_follow', sa.Boolean(), nullable=True),
    sa.Column('link_type', sa.String(length=50), nullable=True),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawls.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_page_id'], ['pages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_links_destination_url'), 'links', ['destination_url'], unique=False)
    op.create_index(op.f('ix_links_id'), 'links', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_id'), table_name='links')
    op.drop_index(op.f('ix_links_destination_url'), table_name='links')
    op.drop_table('links')
    op.drop_index(op.f('ix_images_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_pages_url'), table_name='pages')
    op.drop_index(op.f('ix_pages_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_crawls_id'), table_name='crawls')
    op.drop_table('crawls')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
